#!/bin/bash

echo "All variables passed to the script are stored in a special variable called $@"
echo "All variables passed to the script are stored in a special variable called $."
echo "All variables passed to the script are stored in a special variable called $*"
echo "All variables passed to the script are stored in a special variable called $?"
echo "All variables passed to the script are stored in a special variable called $!"
echo "All variables passed to the script are stored in a special variable called $-"
echo "All variables passed to the script are stored name in a special variable called $0"
echo "All variables passed to the script are stored in a special variable called $1"
echo "All variables passed to the script are stored in a special variable called $2"
echo "current working directory: $PWD"
echo "current user: $USER"
echo "current home directory: $HOME"
echo "current shell: $SHELL"
echo "current process id: $$"
echo "current script name: $0"
echo "current script arguments: $@"
sleep 20 &
echo "get the process id of the last background command: $!"
